### ISSUE TITLE
[Windows] kite:not running

### ISSUE THREAD

**Issue by nyeinsoe26** [kiteco/jupyterlab-kite#36]
Hi, I am having this issue where it shows kite:not running even after I start my kite engine. Is there any way around this? thx

**Comment by plungg** [comment]
@nyeinsoe26 Please wait 15-20 seconds as JupyterLab sometimes takes time to initialize the virtual document. If refreshing the page does not fix the problem, please reply with these logs and we’ll get you up and running!

* Jupyter logs
    * Any logs printed out in the shell if you ran Jupyter via `jupyter lab`
    * Or run `jupyter lab --debug`
* Contents of your browser's console
    * For example, in **Chrome > View > Developer > JavaScript Console**
* The URL to your Kite logs
    * Go to `kite://settings/logs` in your browser
    * Then click **Generate Logs**. Kite uploads your logs to a secure URL that only Kite employees can access.
    * More detailed instructions (https://help.kite.com/article/96-contact-us-with-logs)

**Comment by EricPmWong** [comment]
Same Issue here
Console hangs: here [I 16:55:24.024 LabApp] Build is up to date
[I 16:55:25.222 LabApp] Kernel started: f459fde0-15ab-42d2-847c-13694c79c033, name: python3
/[region= release=] 2020/06/22 16:55:26.413111 main.go:13: Kite-LSP Starting...
\
Browser Console: 
![image](https://user-images.githubusercontent.com/20134310/85334604-87db7280-b4a9-11ea-8b11-ed526626ec82.png)

Kite Logs: https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/357283/kite_local/client.log.2020-06-22_04-58-37-PM.bak.gz

**Comment by ryantberg** [comment]
This seems to be an issue with how our plugin handles file-paths on Windows, and we are currently working on a fix. I will follow up when the fix is released.

**Comment by ryantberg** [comment]
https://github.com/golang/go/issues/32456

**Comment by CNFeffery** [comment]
@ryantberg @nyeinsoe26 @plungg 
After I updated my `jupyterlab` to `3.0.0`, this problem was solved.
![image](https://user-images.githubusercontent.com/49147660/85936032-70790b00-b929-11ea-9142-3bf1be59a6c7.png)

**Comment by CNFeffery** [comment]
> @ryantberg @nyeinsoe26 @plungg
> After I updated my `jupyterlab` to `3.0.0`, this problem was solved.
> ![image](https://user-images.githubusercontent.com/49147660/85936032-70790b00-b929-11ea-9142-3bf1be59a6c7.png)

`jupyterlab 2.2.0a1` is equally effective.

**Comment by ryantberg** [comment]
The fix for Windows users is now available with the latest version of Kite (`20200626`), which went out last night. @CNFeffery switching your JupyterLab version around was likely just a coincidence :)

Marking this as closed. If anyone is still experiencing this issue, please post below.

**Comment by plungg** [comment]
FYI you can see your version number in your copilot. Open it by running `kite://settings` in your browser. The version number is at the bottom
![image](https://user-images.githubusercontent.com/5544312/86037705-a7682300-b9f4-11ea-9c92-0e41434ff166.png)

If you are not automatically on the latest one, the easiest way to force an update is to download Kite again from kite.com/download

**Comment by nyeinsoe26** [comment]
After I redid the set-up for kite and updated the jupyter lab to version 3.0.0a0, it is now working flawlessly. Thanks for all the help.
