### ISSUE TITLE
No completions for JupyterLab

### ISSUE THREAD

**Issue by sergeyFlakon** [kiteco/jupyterlab-kite#39]
Happens on OSX and Linux (Didn't try on Windows yet)

![image](https://user-images.githubusercontent.com/25489358/85346471-298caf00-b4fe-11ea-816a-885a456774ea.png)

Linux:
JupyterLab logs:  [jupyter-lab --debug.zip](https://github.com/kiteco/kiteco/files/4816174/jupyter-lab.--debug.zip)

Kite Logs: https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/373963/kite_local/client.log.2020-06-23_03-04-59-AM.bak.gz

**Comment by ryantberg** [comment]
Not sure what the exact issue is, but you seem to be running an old version of `jupyterlab-kite` (`0.0.1` instead of `0.2.1-a.0`), which could be causing the problem.

**Comment by sergeyFlakon** [comment]
```
pip3 list | grep kite
jupyter-kite                  0.2.1a0
```

**Comment by ryantberg** [comment]
What is the output when you run `jupyter labextension list` ?

**Comment by sergeyFlakon** [comment]
```
$ jupyter labextension list
JupyterLab v2.1.5
Known labextensions:
   app dir: /home/most/anaconda3/envs/spyder-dev/share/jupyter/lab
        @kiteco/jupyterlab-kite v0.2.1-a.0  enabled  OK

```

**Comment by ryantberg** [comment]
Interesting. Not sure why there's an incorrect version printed in your logs.

Either way, the plugin requires JupyterLab v2.2.0 or later, which is currently a pre-release. Having v2.1.5 would definitely prevent you from getting completions.

**Comment by sergeyFlakon** [comment]
@ryantberg yeah, guess I didn't use the --pre flag correctly, anyway with 2.20a is started working

Thanks!

**Comment by Ary276** [comment]
Hi, I think I have a similar issue. I checked the version with jupyter labextension list and it's running an older version. I tried again to install the pre-release version, but it's not working. Could you please tell how can I install the specific version. 
Thank you

**Comment by sergeyFlakon** [comment]
@Ary276 
```
pip3 list | jupy 
pip3 uninstall jupyterlab
pip3 install --pre jupyterlab

```
with first line, you'll see versions installed

**Comment by ryantberg** [comment]
@sergeyFlakon believe you probably meant `pip3 list | grep jupy` for that first line

**Comment by Ary276** [comment]
Thank you. However, Kite is still not running for me.

**Comment by CNFeffery** [comment]
> Interesting. Not sure why there's an incorrect version printed in your logs.
> 
> Either way, the plugin requires JupyterLab v2.2.0 or later, which is currently a pre-release. Having v2.1.5 would definitely prevent you from getting completions.

How can I get `jupyterlab v2.2.0`
